name: job output

on:
  workflow_dispatch:

env:
  PROJECT: project-a

jobs:
  job1:
    name: 메세지를 출력하고, 반환한다.
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.prepare-variables.output.version}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Prepare variables
      id: prepare-variables
      run: |
        set -ex
        REF_NAME=${{ github.ref_name }}
        VERSION=${REF_NAME//\//-}-${{ github.run_number }}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: print variables
      run: |
        echo ${VERSION}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v3
      - name: print variables
        run: | 
          echo ${{needs.job1.outputs.version}}
          echo ${{env.PROJECT}}
