name: need action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: job1
      run: echo job1
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: job2
      run: exit 9
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
    - name: job3
      run: echo job3
