name: pr 머지되면 실행

run-name: pr 머지되면 실행 | ${{ github.event.pull_request.title || github.event_name }}

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        if: |
          (${{github.event_name}} == 'workflow_dispatch') ||
          (${{github.event_name}} == 'pull_request' && ${{github.event.pull_request.merged}} == true && ${{github.base_ref}} == 'main')
        run: echo success
