name: pr 머지되면 실행

run-name: pr 머지되면 실행 | ${{ github.event.pull_request.title || github.event_name }}

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  check:
    runs-on: ubuntu-lastest
    name: 머지할지 체크
    steps:
    - run: echo success
