name: pr 머지되면 실행

run-name: pr 머지되면 실행 | ${{ github.event.pull_request.title || github.event_name }}

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  
jobs:
  job1:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Run a script
        run: echo "실행됨"
  job2:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'  && github.head_ref == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Run a script
        run: echo "실행안됨"
  
