name: pr 머지되면 실행

run-name: pr 머지되면 실행 | ${{ github.event.pull_request.title || github.event_name }}

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME. ${{github.event.inputs.username}}
