name: pr 머지되면 실행

run-name: pr 머지되면 실행 | ${{ github.event.pull_request.title || github.event_name }}

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  job1:
    if: github.event.pull_request.merged == true && github.base_ref == 'main' # The job will only run if the PR is merged and the base branch is 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "PR has been merged into the main branch."
