name: pr 머지되면 실행

run-name: pr 머지되면 실행 | ${{ github.event.pull_request.title || github.event_name }}

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  job-name:
    runs-on: ubuntu-lastest
    steps: 
      - id: step-id
        run: echo "test"
